export type Place = {
  id: number;
  category: "beach" | "food" | "shopping" | "sightseeing";
  name: string;
  features: string[];
};

export const places: Array<Place> = [
  {
    id: 0,
    category: "beach",
    name: "与那覇前浜ビーチ",
    features: ["東洋一の砂浜", "定番", "マリンスポーツ"],
  },
  {
    id: 1,
    category: "beach",
    name: "パイナガマビーチ",
    features: ["ゆったり過ごす", "市街地が近い"],
  },
  {
    id: 2,
    category: "beach",
    name: "新城海岸",
    features: ["サンゴ礁", "シュノーケリング", "家族連れ"],
  },
  {
    id: 3,
    category: "shopping",
    name: "あたらす市場",
    features: ["地産地消", "島バナナ", "島野菜"],
  },
  {
    id: 4,
    category: "shopping",
    name: "島の駅みやこ",
    features: ["お土産", "フードコート"],
  },
  {
    id: 5,
    category: "sightseeing",
    name: "東平安名崎",
    features: ["日の出", "絶景", "大パノラマ"],
  },
  {
    id: 6,
    category: "sightseeing",
    name: "通り池",
    features: ["天然記念物", "パワースポット", "ダイビング"],
  },
  {
    id: 7,
    category: "beach",
    name: "渡口の浜",
    features: ["伊良部島No1ビーチ", "マリンスポーツ"],
  },
  {
    id: 8,
    category: "sightseeing",
    name: "17END",
    features: ["インスタ映え", "SUP", "砂浜"],
  },
  {
    id: 9,
    category: "food",
    name: "古謝そば屋",
    features: ["家族連れ", "人気店"],
  },
  {
    id: 10,
    category: "food",
    name: "麺屋サマー太陽",
    features: ["ラーメン", "自家製麺"],
  },
  {
    id: 11,
    category: "food",
    name: "純喫茶ジュニア",
    features: ["純喫茶", "カツカレー", "レトロ"],
  },
  {
    id: 12,
    category: "food",
    name: "小さな幸せ　サクリ",
    features: ["ミニクロワッサン", "ドライブスルー", "バスチー"],
  },
  {
    id: 13,
    category: "food",
    name: "大和食堂",
    features: ["昔ながらの食堂", "レトロ", "家族連れ"],
  },
  {
    id: 14,
    category: "sightseeing",
    name: "牧山展望台",
    features: ["絶景", "フォトジェニック", "自然"],
  },
  {
    id: 15,
    category: "beach",
    name: "長間浜",
    features: ["サンセット", "来間島", "穴場スポット"],
  },
  {
    id: 16,
    category: "shopping",
    name: "サンエー宮古島シティ",
    features: ["お土産", "ショッピングモール", "宮古空港近く"],
  },
  {
    id: 17,
    category: "shopping",
    name: "ドン・キホーテ 宮古島店",
    features: ["お土産", "品揃え豊富"],
  },
  {
    id: 18,
    category: "shopping",
    name: "イオンタウン宮古南ショッピングセンター",
    features: ["便利", "24時間営業", "お土産"],
  },
  {
    id: 19,
    category: "shopping",
    name: "サンエーショッピングタウン宮古食品館",
    features: ["ローカル", "市街地から近い"],
  },
  {
    id: 20,
    category: "beach",
    name: "博愛わいわいビーチ",
    features: ["ウミガメ", "シュノーケリング", "穴場スポット"],
  },
  {
    id: 21,
    category: "beach",
    name: "中の島ビーチ",
    features: ["サンゴ礁", "下地島", "シュノーケリング"],
  },
  {
    id: 22,
    category: "beach",
    name: "イムギャーマリンガーデン",
    features: ["穏やかな波", "シュノーケリング", "お子様連れ"],
  },
  {
    id: 23,
    category: "beach",
    name: "八重干瀬",
    features: ["サンゴ礁", "天然記念物", "ツアー参加"],
  },
  {
    id: 24,
    category: "food",
    name: "モジャのパン屋",
    features: ["売り切れ必須", "モチモチぎっしり", "手ごねパン"],
  },
  {
    id: 25,
    category: "food",
    name: "ルーラーズタコライス宮古アイランド店",
    features: ["タコライス", "テイクアウト", "スパイシー"],
  },
  {
    id: 26,
    category: "food",
    name: "パーラーレッドドラゴン",
    features: ["ガーリックシュリンプ", "開放的なテラス席"],
  },
  {
    id: 27,
    category: "food",
    name: "なかゆくい商店",
    features: ["紅芋ぱんびん", "伊良部島", "人気店"],
  },
  {
    id: 28,
    category: "food",
    name: "ブルーシールパイナガマ店",
    features: ["ブルーシールアイス", "フォトジェニック"],
  },
  {
    id: 29,
    category: "shopping",
    name: "公設市場",
    features: ["お土産", "ローカル", "市街地から近い"],
  },
  {
    id: 30,
    category: "shopping",
    name: "海美来",
    features: ["紅芋もち", "池間島", "お土産"],
  },
  {
    id: 31,
    category: "shopping",
    name: "かねひで みゃーく平良市場店",
    features: ["ローカル", "安価良品", "お惣菜"],
  },
  {
    id: 32,
    category: "shopping",
    name: "琉球民芸おみやげ品みやこ屋",
    features: ["お土産", "市街地にある", "品揃え豊富"],
  },
  {
    id: 33,
    category: "sightseeing",
    name: "ハッピー防空壕",
    features: ["絶景スポット", "フォトジェニック", "伊良部島"],
  },
  {
    id: 34,
    category: "sightseeing",
    name: "うえのドイツ文化村",
    features: ["文化", "テーマパーク", "遊歩道"],
  },
  {
    id: 35,
    category: "sightseeing",
    name: "島尻のマングローブ林",
    features: ["景勝地", "歴史", "生態系"],
  },
  {
    id: 36,
    category: "sightseeing",
    name: "宮古島海中公園",
    features: ["海中散歩", "家族連れ", "思い出作りに"],
  },
  {
    id: 37,
    category: "sightseeing",
    name: "雪塩ミュージアム",
    features: ["絶景", "フォトジェニック", "自然"],
  },
  {
    id: 38,
    category: "sightseeing",
    name: "比嘉ロードパーク",
    features: ["景勝地", "休憩所", "星空フォト"],
  },
  {
    id: 39,
    category: "food",
    name: "伊良部そば かめ",
    features: ["鰹だし", "古民家", "伊良部島"],
  },
  {
    id: 40,
    category: "food",
    name: "A&W 宮古下里通り店",
    features: ["沖縄ご当地バーガー", "ドライブスルーあり"],
  },
  {
    id: 41,
    category: "food",
    name: "志堅原",
    features: ["肴処", "予約必須", "店内生け簀"],
  },
  {
    id: 42,
    category: "food",
    name: "郷家",
    features: ["三線ライブ", "人気店", "携帯セルフオーダー"],
  },
  {
    id: 43,
    category: "food",
    name: "みゃーく商店",
    features: ["天丼", "昼夜営業", "オーナーが有名人"],
  },
];
